### ISSUE TITLE
Half of the circle is cut off in Edge

### ISSUE THREAD

**Issue by JPumphrey** [lelandpaul/virtual-ringing-room#85]
This is on production, see screenshot. MS Edge only, but everyone using edge seems to have this problem.

![bugreport1](https://user-images.githubusercontent.com/1766512/81597824-3cb84500-93be-11ea-9b87-6fc0c6001a2e.png)

**Comment by lelandpaul** [comment]
What version of Edge is this?

We're also seeing similar issues of Firefox, but only in <=74 (latest is 76); that seems to be related to support for css min()/max(). Based on https://caniuse.com/#feat=mdn-css_types_min, that would make me expect that this would be fixed in Edge >=79, but I'm guessing since you're submitting this that it's not?

**Comment by JPumphrey** [comment]
Could be my version of edge is old
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

Will try updating.

**Comment by JPumphrey** [comment]
Ok, yes. The new version of Edge isn't coming through Windows update, but manually updating to it fixes it. Feel free to close but might be worth an FAQ entry or something.

**Comment by lelandpaul** [comment]
This will be fixed by #86 , which adds a CSS fallback for this case.
